

services:
  api-service:
    image: imageapi:latest
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - mynet

  ai-service:
    image: imageai:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
      IMAGES_DIR: /app/images
    depends_on:
      - rabbitmq
    volumes:
      - /var/www/html/officedd/officedd_photo/images/images_name:/app/images
    deploy:
      replicas: 5
    networks:
      - mynet

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"   # RabbitMQ management UI
      - "5672:5672"     # RabbitMQ AMQP port
    environment:
      RABBITMQ_DEFAULT_USER: skko
      RABBITMQ_DEFAULT_PASS: skkospiderman
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mynet

volumes:
  rabbitmq_data:

networks:
  mynet:
    driver: overlay
