version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: skko
      RABBITMQ_DEFAULT_PASS: skkospiderman
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-service:
    image: imageapi:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
    ports:
      - "8000:8000"
    networks:
      - backend
    deploy:
      replicas: 1

  ai-service:
    image: imageai:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
      IMAGES_DIR: /app/images
    volumes:
      - /var/www/html/officedd/officedd_photo/images/images_name:/app/images
    networks:
      - backend
    deploy:
      replicas: 5

networks:
  backend:
