services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
    depends_on:
      - rabbitmq

  ai-service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
      IMAGES_DIR: /app/images
    depends_on:
      - rabbitmq
    volumes:
      - /var/www/html/officedd/officedd_photo/images/images_name:/app/images
    restart: unless-stopped
    deploy:
      replicas: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: skko
      RABBITMQ_DEFAULT_PASS: skkospiderman
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
