version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: skko
      RABBITMQ_DEFAULT_PASS: skkospiderman
    ports:
      - "5672:5672"
      - "15672:15672"

  api-service:
    image: imageapi:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  ai-service:
    image: python:3.10-slim
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
      IMAGES_DIR: /app/images
    volumes:
      - ./ai-service:/app                 # โค้ด Python ของคุณที่เครื่องจะ mount เข้า /app ใน container
      - /var/www/html/officedd/officedd_photo/images/images_name:/app/images  # รูปภาพ
      - /home/modelAi:/root/.insightface/models     # โมเดล insightface จากเครื่อง mount เข้า container
    working_dir: /app
    command: python main.py
    depends_on:
      - rabbitmq

networks:
  default:
    driver: bridge
