services:
  api-service:
    image: imageapi:latest
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
    depends_on:
      - rabbitmq

  ai-service:
    image: imageai:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
      IMAGES_DIR: /app/images
    depends_on:
      - rabbitmq
    volumes:
      - /var/www/html/officedd/officedd_photo/images/images_name:/app/images
    deploy:
      replicas: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
    environment:
      RABBITMQ_DEFAULT_USER: skko
      RABBITMQ_DEFAULT_PASS: skkospiderman
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
