

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: skko
      RABBITMQ_DEFAULT_PASS: skkospiderman
    ports:
      - "5672:5672"
      - "15672:15672"

  api-service:
    image: imageapi:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  ai-service:
    image: imageai:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
      IMAGES_DIR: /app/images
    volumes:
      - /var/www/html/officedd/officedd_photo/images/images_name:/app/images
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1  # ใน compose ธรรมดา ไม่มี replicas ให้ใช้แค่ 1 container เท่านั้น
