services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: skko
      RABBITMQ_DEFAULT_PASS: skkospiderman
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"     # AMQP protocol port
      - "15672:15672"   # Management UI port
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-service:
    image: imageapi:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    deploy:
      replicas: 1

  ai-service:
    image: imageai:latest
    environment:
      RABBITMQ_URL: amqp://skko:skkospiderman@rabbitmq:5672/
      IMAGES_DIR: /app/images
    depends_on:
      - rabbitmq
    volumes:
      - /var/www/html/officedd/officedd_photo/images/images_name:/app/images
    deploy:
      replicas: 5

volumes:
  rabbitmq_data: